#!/usr/bin/env bash
# This script displays username, user ID, and home directory from /etc/passwd
while IFS=":" read -r user _ uid _ _ home _
do
    printf "%s:%s:%s\n" "$user" "$uid" "$home"
done < /etc/passwd
