#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd using fields split by IFS
while IFS=":" read -r user pass uid gid info home shell
do
    echo "The user $user is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $pass, more info about the user here: $info"
done < /etc/passwd
